version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ${APPLICATIONS}:/var/www
            - ./ssl/:/etc/ssl

### Node and Workspace Container #######################################

    node:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./node
            args:
              - TZ=${NODE_TIMEZONE}
            dockerfile: "Dockerfile"
        volumes_from:
            - applications
        extra_hosts:
            - "dockerhost:${DOCKERHOST}"
            - "localmachine:${LOCALMACHINE}"
            - "${EXTRA_HOST}:127.0.0.1"
        ports:
            - "3000"
            - "${NODE_SSH_PORT}:22"
        tty: true

### Workspace Utilities Container ###########################

    workspace:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./workspace
            args:
                - COMPOSER_GLOBAL_INSTALL=${COMPOSER_GLOBAL_INSTALL}
                - INSTALL_WORKSPACE_SSH=${INSTALL_WORKSPACE_SSH}
                - INSTALL_SOAP=${INSTALL_SOAP}
                - INSTALL_ZIP_ARCHIVE=${INSTALL_ZIP_ARCHIVE}
                - INSTALL_BCMATH=${INSTALL_BCMATH}
                - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
                - INSTALL_MEMCACHED=${INSTALL_MEMCACHED}
                - INSTALL_GETTEXT=${INSTALL_GETTEXT}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
                - INSTALL_MONGO=${INSTALL_MONGO}
                - INSTALL_IMAP=${INSTALL_IMAP}
                - INSTALL_OPCACHE=${INSTALL_OPCACHE}
                - INSTALL_EXIF=${INSTALL_EXIF}
                - INSTALL_AEROSPIKE_EXTENSION=${INSTALL_AEROSPIKE_EXTENSION}
                - CODEIGNITER=${CODEIGNITER}
                - PUID=1000
                - PGID=1000
                - TZ=${TZ}
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:${DOCKERHOST}"
            - "localmachine:${LOCALMACHINE}"
            - "${EXTRA_HOST}:127.0.0.1"
        ports:
           - "${WORKSPACE_SSH_PORT}:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./php-fpm
            args:
                - INSTALL_SOAP=${INSTALL_SOAP}
                - INSTALL_ZIP_ARCHIVE=${INSTALL_ZIP_ARCHIVE}
                - INSTALL_BCMATH=${INSTALL_BCMATH}
                - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
                - INSTALL_MEMCACHED=${INSTALL_MEMCACHED}
                - INSTALL_GETTEXT=${INSTALL_GETTEXT}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
                - INSTALL_MONGO=${INSTALL_MONGO}
                - INSTALL_IMAP=${INSTALL_IMAP}
                - INSTALL_OPCACHE=${INSTALL_OPCACHE}
                - INSTALL_EXIF=${INSTALL_EXIF}
                - INSTALL_AEROSPIKE_EXTENSION=${INSTALL_AEROSPIKE_EXTENSION}
                - CODEIGNITER=false
            dockerfile: Dockerfile-${PHP_VERSION}
        volumes_from:
            - applications
        ports:
            - "${PHP_FPM}:9000"
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:${DOCKERHOST}"
            - "localmachine:${LOCALMACHINE}"
            - "${EXTRA_HOST}:127.0.0.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel

### Nginx Server Container ##################################

    nginx:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./nginx
        volumes_from:
            - applications
        volumes:
            - nginx:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        depends_on:
            - apache2

### Nginx Server Container ##################################

    nginx-node:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./nginx
        volumes_from:
            - applications
        volumes:
            - nginx:/var/log/nginx
            - ./nginx/sites-node/:/etc/nginx/sites-available
            - ./nginx/conf.d-node/:/etc/nginx/conf.d
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        depends_on:
            - node

### Apache Server Container #################################

    apache2:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./apache2
            args:
                - PHP_SOCKET=php-fpm:9000
        volumes_from:
            - applications
        volumes:
            - apache2:/var/log/apache2
        ports:
            - "80"
            - "443"
        depends_on:
            - php-fpm


### MySQL Container #########################################

    mysql:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=${DB_NAME}
                - MYSQL_USER=${DB_USER}
                - MYSQL_PASSWORD=${DB_PASS}
                - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
        volumes:
            - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"

### MariaDB Container #######################################

    mariadb:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./mariadb
        volumes:
            - ${DATA_SAVE_PATH}/mariadb:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}


### Mailhog Container #########################################

    mailhog:
      hostname: localhost
      dns:
        - "8.8.8.8"
        - "8.8.4.4"
      dns_search: '' #fix for windows dns resolve.conf
      build: ./mailhog
      ports:
        - "1025:1025"
        - "8025:8025"

### MongoDB Container #######################################

    mongo:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./mongo
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - ${MONGODB_SAVE_PATH}:/data/db
            - mongo:/var/log/mongodb/
        entrypoint:
            - "mongod"
        # The first time comment out the auth section to setup a user
        # Afterwards enable the auth section for security
        #  - "--auth"


### Redis Container #########################################

    redis:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./redis
        volumes:
            - redis:/data
        ports:
            - "${REDIS_PORT}:6379"


### Memcached Container #####################################

    memcached:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./memcached
        volumes:
            - memcached:/var/lib/memcached
        ports:
            - "${MEMCACHED_PORT}:11211"
        links:
            - php-fpm

### Beanstalkd Container ####################################

    beanstalkd:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./beanstalkd
        ports:
            - "${BEANSTALKD_PORT}:11300"
        privileged: true
        links:
            - php-fpm


### Beanstalkd Console Container ############################

    beanstalkd-console:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./beanstalkd-console
        ports:
            - "${BEANCONSOLE_PORT}:2080"
        links:
            - beanstalkd

### phpMyAdmin Container ####################################

    phpmyadmin:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        links:
            - "${DB_HOST}:db"

### ElasticSearch Container #################################

    elasticsearch:
        hostname: localhost
        dns:
          - "8.8.8.8"
          - "8.8.4.4"
        dns_search: '' #fix for windows dns resolve.conf
        build: ./elasticsearch
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
            - elasticsearch-plugins:/usr/share/elasticsearch/data
        ports:
            - "${ELASTICSEARCH_PORT}:9200"
            - "9300:9300"
        links:
            - php-fpm

### Volumes Setup ###########################################

volumes:
    apache2:
        driver: "local"
    nginx:
        driver: "local"
    memcached:
        driver: "local"
    redis:
        driver: "local"
    mongo:
        driver: "local"
    elasticsearch-data:
        driver: "local"
    elasticsearch-plugins:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"
