version: "3.7"

## Volumes Setup

volumes:
    apache2:
        driver: "local"
    nginx:
        driver: "local"

## Services Setup

services:

  ### Workspace Utilities Container ###########################

  workspace:
    hostname: workspace
    image: ignatisd/workspace:${WORKSPACE_PHP_VERSION}
    volumes:
      - ${APPLICATIONS}:/var/www
      - ./ssl/:/etc/ssl
    tty: true

  ### PHP-FPM Container #######################################

  php-fpm:
    hostname: php-fpm
    image: ignatisd/php-fpm:${PHP_VERSION}
    volumes:
      - ${APPLICATIONS}:/var/www
      - ./ssl/:/etc/ssl
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG=serverName=laravel

  ### Nginx Server Container ##################################

  http:
    hostname: http
    image: nginx:${NGINX_VERSION:-1.19.2}
    volumes:
      - ${APPLICATIONS}:/var/www
      - ./ssl/:/etc/ssl
      - nginx:/var/log/nginx
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
        mode: host
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
        mode: host

  ### Apache Server Container #################################

  apache2:
    hostname: apache2
    image: ignatisd/apache2
    build:
      context: ./apache2
      args:
        - PHP_SOCKET=php-fpm:9000
    volumes:
      - ${APPLICATIONS}:/var/www
      - ./ssl/:/etc/ssl
      - apache2:/var/log/apache2
